#users
###
GET  http://localhost:8000/api/users
Authorization: Bearer eyJ

### 
POST http://localhost:8000/api/register
Content-Type: application/json

{ 
  "userId":1,
  
    "name": "Zena Taaka Juma",
    "username": "Bradley",
    "contact_phone": "0745577489",
    "phone_verified":false,
    "email": "zenataaka@gmail.com",
    "email_verified": true,
    "confirmation_code": "8567",
    "password": "Taaka341"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "Bradley",
    "password": "Taaka341"
}
###
PUT  http://localhost:8000/api/users/1
Content-Type: application/json

{
    "name": "john bradill",
    "contact_phone": "0112177489",
    "phone_verified":false,
    "email": "johbradill67@gmail.com",
    "email_verified": true,
    "confirmation_code": "6789",
    "password": "x3h3y8"

}

###
DELETE   http://localhost:8000/api/users/7

###
GET  http://localhost:8000/api/restaurants/2

###

POST   http://localhost:8000/api/restaurants
Content-Type: application/json


{  "id": 2,
  "name": "Chez Panisse",
  "street_address": "2436",
  "zip_code": "9001",
  "city_id": 2
}
###

PUT    http://localhost:8000/api/restaurants/2
Content-Type: application/json

{
  "name": "Chez Panisse",
  "street_address": "2435",
  "zip_code": "9001",
  "city_id": 2
}
###

DELETE     http://localhost:8000/api/restaurants/2

#states
###
GET  http://localhost:8000/api/states/2

###
POST http://localhost:8000/api/states
Content-Type: application/json


{
  "id":"2",
  "name": "Western-Kenya",
  "code": "254"
}

###
PUT   http://localhost:8000/api/states/2
Content-Type: application/json


{
  "id":"2",
  "name": "WesternKenya",
  "code": "254"
}

###
DELETE   http://localhost:8000/api/states/2


# cities
###
GET  http://localhost:8000/api/cities/



###
POST  http://localhost:8000/api/cities
Content-Type: application/json


{  "id":"1",
  "name": "Los Angeles",
  "state_id": 1
}


###
PUT  http://localhost:8000/api/cities/4
Content-Type: application/json


{ "id":"3",
  "name": "KachMega",
  "state_id": 2
}


###
DELETE   http://localhost:8000/api/cities/1
Content-Type: application/json


# Orders
###
GET  http://localhost:8000/api/orders/1

###

POST   http://localhost:8000/api/orders
Content-Type: application/json

{
  "id": 1,
  "restaurant_id": 2,
  "estimated_delivery_time": "2024-06-07T18:30:00.000Z",
  "actual_delivery_time": "2024-06-06T18:50:00.000Z",
  "delivery_address_id": 1,
  "user_id": 1,
  "driver_id": 1,
  "price": "90.00",
  "discount": "10.00",
  "final_price": "80.00",
  "comment": "Delivered",
  "created_at": "2024-06-12T13:55:08.223Z",
  "updated_at": "2024-06-12T13:55:08.223Z"
}

###
PUT   http://localhost:8000/api/orders/1
Content-Type: application/json

{  "id": 1,
  "restaurant_id": 2,
  "estimated_delivery_time": "2024-06-07 18:30:00",
  "actual_delivery_time": "2024-06-06 18:50:00",
  "delivery_address_id": 2,
  "user_id": 2,
  "driver_id": 2,
  "price": 32.99,
  "discount": 0.00,
  "final_price": 32.99,
  "comment": "No onions"
}

###
DELETE    http://localhost:8000/api/orders/


# Order Menu Items
###
GET  http://localhost:8000/api/order_menu_items/1

###
POST  http://localhost:8000/api/order_menu_items
Content-Type: application/json

{
  "order_id": 2,
  "menu_item_id": 2,
  "quantity": 2,
  "item_price": 10,
  "price": 25,
  "comment": "very delicious"
}

###
PUT  http://localhost:8000/api/order_menu_items/1
Content-Type: application/json

{
  "order_id": 2,
  "menu_item_id": 3,
  "quantity": 1,
  "item_price": 8.99,
  "price": 8.99,
  "comment": "No cheese"
}

###
DELETE  http://localhost:8000/api/order_menu_items/1
Content-Type: application/json

{
  "order_id": 2,
  "menu_item_id": 3,
  "quantity": 1,
  "item_price": 8.99,
  "price": 8.99,
  "comment": "No cheese"
}

# Order Statuses
###
GET  http://localhost:8000/api/order_statuses/1

###
POST  http://localhost:8000/api/order_statuses
Content-Type: application/json

{
  "order_id": 1,
  "status_catalog_id": 1
}

###
PUT  http://localhost:8000/api/order_statuses/1
Content-Type: application/json

{
  "order_id": 2,
  "status_catalog_id": 3
}

###
DELETE  http://localhost:8000/api/order_statuses/6
Content-Type: application/json

{
  "order_id": 2,
  "status_catalog_id": 3
}

# Status Catalogs
###
GET  http://localhost:8000/api/status_catalogs/1

###
POST  http://localhost:8000/api/status_catalogs
Content-Type: application/json

{
  "name": "Delivered"
}

###
PUT  http://localhost:8000/api/status_catalogs/
Content-Type: application/json

{
  "name": "Cancelled"
}

###
DELETE  http://localhost:8000/api/status_catalogs/
Content-Type: application/json

{
  "name": "Cancelled"
}

# Comments
###
GET  http://localhost:8000/api/comments/1

###
POST  http://localhost:8000/api/comments
Content-Type: application/json

{
  "user_id": 1,
  "order_id": 1,
  "comment": "Great service",
  "is_complaint": false,
  "is_praise": true
}

###
PUT  http://localhost:8000/api/comments/1
Content-Type: application/json

{
  "user_id": 2,
  "order_id": 2,
  "comment": "Late delivery",
  "is_complaint": true,
  "is_praise": false
}

###
DELETE  http://localhost:8000/api/comments/1
Content-Type: application/json

{
  "user_id": 2,
  "order_id": 2,
  "comment": "Late delivery",
  "is_complaint": true,
  "is_praise": false
}

# Categories
###
GET  http://localhost:8000/api/categories/3

###
POST  http://localhost:8000/api/categories
Content-Type: application/json

{  "id": 5,
  "name": "Fried Meals"
}

###
PUT  http://localhost:8000/api/categories/1
Content-Type: application/json

{
  "name": "Soft Drinks"
}

###
DELETE  http://localhost:8000/api/categories/1
Content-Type: application/json
  
  {
    "name": "accesories"
  }

# Restaurant Owners
###
GET  http://localhost:8000/api/restaurant_owners/2

###
POST  http://localhost:8000/api/restaurant_owners
Content-Type: application/json

{ 
  "restaurant_id": 2,
  "owner_id": 1
}

###
PUT  http://localhost:8000/api/restaurant_owners/2
Content-Type: application/json

{ "id":"2",
  "restaurant_id": 1,
  "owner_id": 2
}

###
DELETE  http://localhost:8000/api/restaurant_owners/1/1
Content-Type: application/json

{
  "restaurant_id": 1,
  "owner_id": 1
}

# Addresses
###
GET  http://localhost:8000/api/addresses/1

###
POST  http://localhost:8000/api/addresses
Content-Type: application/json

{
  "id": 1,
  "street_address_1": "2345",
  "street_address_2": "2345 Los Angeles",
  "zip_code": "1",
  "delivery_instructions": "Deliver at the gate",
  "user_id": 1,
  "city_id": 1
}

###
PUT  http://localhost:8000/api/addresses/2
Content-Type: application/json

{  
  "id": 2,
  "street_address_1": "2435",
  "street_address_2": "2435 San Diego",
  "zip_code": "9001",
  "delivery_instructions": "Deliver at the door",
  "user_id": 1,
  "city_id": 2
}

###
DELETE  http://localhost:8000/api/addresses/1


# Drivers
###
GET  http://localhost:8000/api/drivers/1

###
POST  http://localhost:8000/api/drivers
Content-Type: application/json

{  "id": 1,
  "car_make": "BMW",
  "car_model": "G20",
  "car_year": "2022",
  "user_id": 2,
  "online": false,
  "delivering": true
}

###
PUT  http://localhost:8000/api/drivers/
Content-Type: application/json

{
  "car_make": "BMW",
  "car_model": "G20",
  "car_year": 2022,
  "user_id": 2,
  "online": false,
  "delivering": true
}

###
DELETE  http://localhost:8000/api/drivers/

# Menu Items
###
GET  http://localhost:8000/api/menu_items/1

###
POST  http://localhost:8000/api/menu_items
Content-Type: application/json

{ "id": 1,
  "name": "piza",
  "restaurant_id": 1,
  "category_id": 1,
  "description": "Italy Pizare",
  "ingredients": "Beef, cassava, Tomato, meat",
  "price": 90,
  "active": true
}

###
PUT  http://localhost:8000/api/menu_items/1
Content-Type: application/json

{
  "name": "dry Tilapia ",
  "restaurant_id": 2,
  "category_id": 2,
  "description": "Tilapia dry",
  "ingredients": "tulapia,Lettuce, Tomato, onions",
  "price": 10.99,
  "active": true
}

###
DELETE  http://localhost:8000/api/menu_items/1

  
  ###
GET  http://localhost:8000/api/menu_items/1

# ###
# POST  http://localhost:8000/api/register
# Content-Type: application/json

# {  
#     "userId":1,
#     "email": "zenataaka@gmail.com",
#     "password": "Taaka341",
#     "role":"user"
# }
